version: '3.8'

services:
  card-analyzer-app:
    build: .
    container_name: credit-card-analyzer
    ports:
      - '8501:8501'
    env_file:
      - ../../.env
    volumes:
      - ./src:/app/src # Hot-reload para desenvolvimento
      - ./data:/app/data # Persistência do banco SQLite
    restart: unless-stopped
